export const STAGES = [
  {
    id: 'signup',
    label: '1. Signup',
    short: 'Signup',
    desc: 'Your <b>forms</b> for new referrals and how people <b>register</b>',
    pillBg: '#FFF8EE',
    pillTx: '#854F0B',
    headBg: '#FFF8EE',
    icon: '/icons/icon_signup.png',
  },
  {
    id: 'assess',
    label: '2. Assess',
    short: 'Assess',
    desc: "How you decide a participant's <b>suitability</b> for a service and identify their <b>needs</b>",
    pillBg: '#EEF4FF',
    pillTx: '#185FA5',
    headBg: '#EEF4FF',
    icon: '/icons/icon_assess.png',
  },
  {
    id: 'assign',
    label: '3. Assign',
    short: 'Assign',
    desc: 'How you assign participants to specific <b>colleagues</b> and <b>services</b> including to a <b>waiting list</b>',
    pillBg: '#EEFFF6',
    pillTx: '#3B6D11',
    headBg: '#EEFFF6',
    icon: '/icons/icon_assign.png',
  },
  {
    id: 'inform',
    label: '4. Inform',
    short: 'Inform',
    desc: 'How you tell participants the details of <b>when</b> and <b>where</b> they will be receiving the service',
    pillBg: '#F0EEFF',
    pillTx: '#534AB7',
    headBg: '#F0EEFF',
    icon: '/icons/icon_inform.png',
  },
  {
    id: 'provide',
    label: '5. Provide',
    short: 'Provide',
    desc: 'How you <b>schedule</b>, <b>deliver</b> and <b>monitor</b> the support being provided',
    pillBg: '#EEFFF6',
    pillTx: '#0F6E56',
    headBg: '#EEFFF6',
    icon: '/icons/icon_provide.png',
  },
  {
    id: 'reassess',
    label: '6. Re-assess',
    short: 'Re-assess',
    desc: 'Other information you <b>collect</b> or <b>track over time</b> e.g. to show how the participant is improving',
    pillBg: '#FFF0F5',
    pillTx: '#993556',
    headBg: '#FFF0F5',
    icon: '/icons/icon_reassess.png',
  },
  {
    id: 'complete',
    label: '7. Complete',
    short: 'Complete',
    desc: "What happens at the end of a participant's use of this service",
    pillBg: '#F5F5F5',
    pillTx: '#5F5E5A',
    headBg: '#F5F5F5',
    icon: '/icons/icon_complete.png',
  },
]
